name: 'Smash League | Scheduled'

on: push
  # schedule:
  #   - cron:  '0 6 * * *'

jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Cache Docker image
        uses: actions/cache@v1
        id: cached-docker-build
        with:
          path: docker-cache/
          key: ${{ runner.os }}-docker-${{ hashFiles('**/package*.json')}}

      - name: Build the Docker image
        if: steps.cached-docker-build.outputs.cache-hit != 'true'
        run: docker build . --file Dockerfile --build-arg NODE_ENV=prod --tag smash-league

      - name: Save Docker image into file
        if: steps.cached-docker-build.outputs.cache-hit != 'true'
        run: |
          mkdir docker-cache 
          docker save -o docker-cache/smash-league-docker-image.tar smash-league 

      # - name: Persist Docker image file
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: smash-league-docker-image
      #     path: docker-cache/smash-league-docker-image.tar


  run:
    name: 'Run League'
    needs: build
    runs-on: ubuntu-latest

    env: 
      WIT_TOKEN: ${{ secrets.WIT_TOKEN }}
      SLACK_API_TOKEN:  ${{ secrets.SLACK_API_TOKEN }}
    
    steps:      
      - uses: actions/checkout@v1

      - name: Cache Docker image
        uses: actions/cache@v1
        with:
          path: docker-cache/
          key: ${{ runner.os }}-docker-${{ hashFiles('**/package*.json')}}

      - name: Load Docker image file
        run: docker load -i docker-cache/smash-league-docker-image.tar
      
      - name: Run league code
        run: >-
          docker run
          --name smash-league
          -e SLACK_API_TOKEN=${SLACK_API_TOKEN}
          -e WIT_TOKEN=${WIT_TOKEN}
          -v ranking-info:/usr/app/ranking-info
          -v src:/usr/app/src
          smash-league
          npm run start:smash-league
# -e TRAVIS_BRANCH="master"
# -e CI=true

      - name: Extract ranking info
        run: | 
          mkdir new-ranking-info
          docker cp smash-league:/usr/app/ranking-info/. new-ranking-info/
      
      - name: Save files
        uses: actions/upload-artifact@v1
        with:
          name: ranking-info
          path: ./new-ranking-info/

  commit:
    name: 'Commit new ranking'
    needs: run
    runs-on: ubuntu-latest

    env: 
      REMOTE_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      REMOTE_REF: ${{ github.ref }}
      STUFF: ${{ toJson(github) }}

    steps:
      - uses: actions/checkout@v1

      - name: Check structure
        run: echo ${STUFF}

      - name: Clean old ranking-info
        run: rm -rf ranking-info

      - name: Download new ranking info
        uses: actions/download-artifact@v1
        with:
          name: ranking-info

      - name: Commit back new ranking info
        run: |
          git config user.name "github"
          git config user.email "github@users.noreply.github.com"
          git add .
          git commit -m 'Auto pushed from Github Actions'
          git push ${REMOTE_REPO} HEAD:${REMOTE_REF}
