name: 'Smash League | Scheduled'

on: push
  # schedule:
  #   - cron:  '0 6 * * *'

jobs:
  main:
    name: 'Run League'

    env: 
      WIT_TOKEN: ${{ secrets.WIT_TOKEN }}
      SLACK_API_TOKEN:  ${{ secrets.SLACK_API_TOKEN }}

    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg NODE_ENV=prod --tag smash-league
      
      - name: Run league code
        run: >-
          docker run
          --name smash-league
          -e SLACK_API_TOKEN=${SLACK_API_TOKEN}
          -e WIT_TOKEN=${WIT_TOKEN}
          smash-league
          npm run start:smash-league
# -e TRAVIS_BRANCH="master"
# -e CI=true

      - name: Extract ranking info
        run: | 
          mkdir hola-morro
          pwd
          ls 
          docker cp smash-league:/usr/app/ranking-info/. hola-morro/ranking-info/

      - name: Show structure
        run: |
          ls
          ls hola-morro
      
      - name: Save files
        uses: actions/upload-artifact@v1
        with:
          name: ranking
          path: ./hola-morro/ranking-info/
