name: Run League

on: [pull_request]
# on: 
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  main:
    name: 'Run League'
    # if: github.ref == 'refs/heads/github-actions'
    
    env: 
      WIT_TOKEN: ${{ secrets.WIT_TOKEN }}
      SLACK_API_TOKEN:  ${{ secrets.SLACK_API_TOKEN }}
      STUFF:  ${{ toJson(github) }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Debug
        run: echo ${STUFF}
      
      # - uses: actions/checkout@v1

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --build-arg NODE_ENV=prod --tag smash-league
      
      # - name: Run league code
      #   run: >-
      #     docker run
      #     --name smash-league-bot
      #     -e SLACK_API_TOKEN=${SLACK_API_TOKEN}
      #     -e WIT_TOKEN=${WIT_TOKEN}
      #     smash-league
      #     npm run start:smash-league

