name: 'Smash League | Scheduled'

on: push
  # schedule:
  #   - cron:  '0 6 * * *'

jobs:


 build:
    name: 'Build'

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Cache Docker image
        uses: actions/cache@v1
        id: cached-docker-build
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-docker-${{ hashFiles('**/package*.json')}}

      - name: Build the Docker image
        if: steps.cached-docker-build.outputs.cache-hit != 'true'
        run: docker build . --file Dockerfile --build-arg NODE_ENV=prod --tag smash-league

      - name: Save Docker image into file
        if: steps.cached-docker-build.outputs.cache-hit != 'true'
        run: docker save -o smash-league-docker-image smash-league 


      - name: Persist Docker image file
        uses: actions/upload-artifact@v1
        with:
          name: smash-league-docker-image
          path: smash-league-docker-image


  run:
    name: 'Run League'
    needs: build
    runs-on: ubuntu-latest

    env: 
      WIT_TOKEN: ${{ secrets.WIT_TOKEN }}
      SLACK_API_TOKEN:  ${{ secrets.SLACK_API_TOKEN }}
    
    steps:      
      - uses: actions/checkout@v1

      - name: Restore Docker image file
          uses: actions/download-artifact@v1
          with:
            name: smash-league-docker-image

      - name: Load Docker image file
        run: docker load -i smash-league-docker-image

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --build-arg NODE_ENV=prod --tag smash-league
      
      - name: Run league code
        run: >-
          docker run
          --name smash-league
          -e SLACK_API_TOKEN=${SLACK_API_TOKEN}
          -e WIT_TOKEN=${WIT_TOKEN}
          smash-league
          npm run start:smash-league
# -e TRAVIS_BRANCH="master"
# -e CI=true

      - name: Extract ranking info
        run: | 
          mkdir hola-morro
          pwd
          ls 
          docker cp smash-league:/usr/app/ranking-info/. hola-morro/

      - name: Show structure
        run: |
          ls
          ls hola-morro
      
      - name: Save files
        uses: actions/upload-artifact@v1
        with:
          name: ranking
          path: ./hola-morro/ranking-info/
